from MLHelper import constants as const

project_config = {
	"test_model_path": "test_models/",
	"data_base": "data/",
	const.LABEL_NAME: "label_1",
	const.RUN_FOLDER: "runs/",
	const.FILENAME_RUN_CONFIG: const.FILENAME_RUN_CONFIG_VALUE,
	const.FILENAME_LOG_OUTPUT: const.FILENAME_LOG_OUTPUT_VALUE,
	const.LOAD_PREVIOUS_RUN_NAME: "",
	const.CHUNK_DURATION: 7.0,
	const.TASK_TYPE: const.TASK_TYPE_TRAINING,
	const.RUN_NAME: "blank_name",
	const.METADATA_FRAC: 1.0,
	const.TRAIN_FRAC: 0.8,
	const.MODEL_TYPE: const.CNN,
	const.TRAIN_DATASET: const.PHYSIONET_2016,
	const.INFERENCE_DATASET: const.PHYSIONET_2022,
	const.INFERENCE_MODEL: "",
	const.AUGMENTATION_RATE: 0.65,
	const.NUM_WORKERS: 0,
	const.MODEL_SUB_TYPE: 1,
	const.KFOLD_SPLITS: 5,
	const.CNN_PARAMS: {
		const.DROP0: 0.5,
		const.DROP1: 0.2,
		const.ACTIVATION: const.ACTIVATION_SILU,
		const.OPTIMIZER: const.OPTIMIZER_SGD,
		const.LOSS_FUNCTION: const.LOSS_FOCAL_LOSS,
		const.EPOCHS: 10,
		const.BATCH_SIZE: 32,
		const.LEARNING_RATE: 0.001,
		const.N_MELS: 512,
		const.HOP_LENGTH: 128,
		const.N_FTT: 1024,
		const.TOP_DB: 80,
		const.SIGNAL_FILTER: const.BUTTERPASS,
		const.BUTTERPASS_LOW: 25,
		const.BUTTERPASS_HIGH: 400,
		const.BUTTERPASS_ORDER: 4,

	},
}