test_model_path: test_models/
data_base: data/
label_name: label_1
run_folder: runs/
config_filename: run_config.yaml
log_output_filename: run_output.log
load_config_from_run_name: 

n_mels: 50
hop_length: 50
n_ftt: 50
top_db: 50

task_type: training
run_name: blank_name