from MLHelper import constants as const

project_config = {
	"test_model_path": "test_models/",
	"data_base": "data/",
	const.LABEL_NAME: "label_1",
	const.RUN_FOLDER: "runs/",
	const.FILENAME_RUN_CONFIG: const.FILENAME_RUN_CONFIG_VALUE,
	const.FILENAME_LOG_OUTPUT: const.FILENAME_LOG_OUTPUT_VALUE,
	const.LOAD_PREVIOUS_RUN_NAME: "",
	const.CHUNK_DURATION: 10,
	const.TASK_TYPE: const.TASK_TYPE_TRAINING,
	const.RUN_NAME: "blank_name",
	const.METADATA_FRAC: 0.1,
	"model_type": "cnn",
	"train_dataset": "physionet2016",
	"inference_dataset": "physionet2016",
	"inference_model": "",
	const.AUGMENTATION_RATE: 0.5,
	const.NUM_WORKERS: 0,
	const.MODEL_SUB_TYPE: 1,
	const.CNN_PARAMS: {
		const.DROP0: 0.5,
		const.DROP1: 0.5,
		const.ACTIVATION: "relu",
		const.OPTIMIZER: "sgd",
		const.LOSS_FUNCTION: "FocalLoss",
		const.EPOCHS: 10,
		const.BATCH_SIZE: 32,
		const.LEARNING_RATE: 0.001,
		const.N_MELS: 50,
		const.HOP_LENGTH: 50,
		const.N_FTT: 50,
		const.TOP_DB: 50,
		const.SIGNAL_FILTER: const.BUTTERPASS,
		const.BUTTERPASS_LOW: 20,
		const.BUTTERPASS_HIGH: 500,
		const.BUTTERPASS_ORDER: 4,

	},
}