line-length = 110

[format]
# Use tabs instead of 4 space indentation.
indent-style = "tab"
exclude = [
	"runs",
	"data",
	"audio_example_images",
]

# https://docs.astral.sh/ruff/rules/
[lint]
select = [
    
    "E",  # pycodestyle
    
    "F",  # Pyflakes
    
    "UP", # pyupgrade
    
    "B",  # flake8-bugbear
    
    "N",  # Naming
    "SIM",# flake8-simplify

    "W", # Whitespaces

    "I", # Unused Imports

    "UP", # Pyupgrade

    "EM", 

    "PIE", # flake8-pie

    "T20", 

    "Q", # flake8-quotes

    "RSE",

    "RET", 
    "INT",
    "PTH", # use pathlib
    "PL", 
    "RUF", # ruff

]

ignore = ["F541","F821", "F403", "F405", "W191", "EM101", "EM102", "RUF012", "RET504", "PLR2004"]
task-tags = ["TODO"]

[lint.flake8-annotations]
allow-star-arg-any = true